### ISSUE TITLE
Build errors on Windows

### ISSUE THREAD

**Issue by huisinro** [irdvo/gpxlib#1]
Can't build on Windows out of box, but easy to make it to work. 

I modified a bit to make it to work on Windows. Do you want to merge the patch?

**Comment by irdvo** [comment]
Yes, that is okee.

2016-09-02 19:27 GMT+02:00 Huihong Luo notifications@github.com:

**Comment by huisinro** [comment]
Hi,
I've attached the modified source code, you can use gitk to look at the changes.
Thanks,
- Huihong

**Comment by irdvo** [comment]
Hello,

I'm sorry, but I am missing the attachment. Can you send it again ?

Thanks,
Dick

2016-09-02 22:54 GMT+02:00 Huihong Luo notifications@github.com:

**Comment by huisinro** [comment]
Hi Dick,
I've put it to the google drive:
https://drive.google.com/file/d/0B0R9HPU9wNfmV19LSy16N1RVb2c/view?usp=sharing

Thanks,
- Huihong

**Comment by irdvo** [comment]
Hello,

I have downloaded it and I will merge it.

Thanks,
Dick

2016-09-03 6:53 GMT+02:00 Huihong Luo notifications@github.com:

**Comment by irdvo** [comment]
Hello,

Thanks for the changes. It looks very good.

I removed the strings.h includes, linux doesn't need them either.

I merged the bug fixes in Parser and the changes in CMakeListst.txt for
install.

I understand that String.h result in problems on Windows. I am still
looking for a better name than MyString. I was thinking about xsdString,
but not sure.

Thanks,
Dick

2016-09-03 7:01 GMT+02:00 Dick van Oudheusden dvoudheusden@gmail.com:

**Comment by huisinro** [comment]
That's nice, I am trying to use your project inside a Windows program that can be use to simulate GPS location for iOS, I will update you in a few days on the project.

**Comment by huisinro** [comment]
There still some error in CMakeFile.list, I needed to manually modify vs2015 project properties. gpx should be static library, and those example projects should add expat lib. you can correct these two issues in make files.

**Comment by huisinro** [comment]
I also added this define flag manually to VS2015 preprocessors:
strcasecmp=_stricmp

```
  From: irdvo <notifications@github.com>
```

 To: irdvo/gpxlib gpxlib@noreply.github.com 
Cc: Huihong Luo huisinro@yahoo.com; Author author@noreply.github.com
 Sent: Friday, September 2, 2016 11:10 PM
 Subject: Re: [irdvo/gpxlib] Build errors on Windows (#1)

Hello,

Thanks for the changes. It looks very good.

I removed the strings.h includes, linux doesn't need them either.

I merged the bug fixes in Parser and the changes in CMakeListst.txt for
install.

I understand that String.h result in problems on Windows. I am still
looking for a better name than MyString. I was thinking about xsdString,
but not sure.

Thanks,
Dick

2016-09-03 7:01 GMT+02:00 Dick van Oudheusden dvoudheusden@gmail.com:

**Comment by irdvo** [comment]
Hello,

I changed the makefile for static library building for windows. I also
added a define for strcasecmp in the code.

I am not sure why the examples aren't able to use expat. In the cmake file
in the examples the library is searched and added to the linker. Possible
that the expat include file cannot be used, so I added that to the cmake
file.

Thanks,
Dick
