### ISSUE TITLE
Lack of Extension for Waypoints

### ISSUE THREAD

**Issue by mr337** [irdvo/gpxlib#2]
I have a GPX file (v1.1) that has extentions on the trkpt, that looks like this:
```
<trkpt lat="XX" lon="XX">
<link ></link>
<extensions>
    <type>cut</type>
    <pass_through>True</pass_through>
</extensions>
</trkpt>
```
Checking the schema it looks like a trackpoint gets is a [waypoint](http://www.topografix.com/GPX/1/1/#type_wptType) wrapped. I can't seen to access the extension and get errors for every trackpoint.
```
Element trkpt : Unknown child node added: extensions.
Element trkpt : Unknown child node added: extensions.
.
.
```

**Comment by mr337** [comment]
@irdvo I saw the commits to master, and I'll test this on some of our GPX files and report back with any issues. (If that helps!)

**Comment by irdvo** [comment]
Okee

2018-06-04 22:10 GMT+02:00 Lee Hicks <notifications@github.com>:

**Comment by mr337** [comment]
I am still having issues with printing the GPX v1.1 extensions. Sample gpx files is defined as:
```
<?xml version="1.0" encoding="utf-8"?>
<gpx>
  <trk>
    <name>Test</name>
    <trkseg>
      <trkpt lat="50.7" lon="6.4">
        <extensions>
          <pass_through>True</pass_through>
        </extensions>
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```

With the modifications in PR https://github.com/irdvo/gpxlib/pull/3 the output is
```
$ ./gpxtrk /tmp/test.gpx
Track:1
  Name        : Test
  Comment     : 
  Description : 
  Source      : 
  Type        : 
  Number      : 
  Segments:   : 1

  Segment     : 1
    Latitude    Longitude   Elevation   Time                 Name     Comment    Extension  
           50.7         6.4                                  trkpt                          
```

So looks like trackpoint extension info isn't getting pulled in. Any thoughts?

**Comment by irdvo** [comment]
If you look at the show(...) function in gpxtrk, you see that it is calling
getValue(). So it will call the getValue() of the extensions. But the value
of the extensions is empty, it has only one element (<pass_through>).

If you change the xml in:

<?xml version="1.0" encoding="utf-8"?>
<gpx>
  <trk>
    <name>Test</name>
    <trkseg>
      <trkpt lat="50.7" lon="6.4">
        <extensions>Hello</extensions>
      </trkpt>
    </trkseg>
  </trk>
</gpx>

It will show 'Hello' for extensions.


If you want to see the <pass_through> element, you should iterate the
extensions()->getElements(). For example:

for (list<gpx::Node*>::const_iterator iter =
extensions()->getElements().begin(); iter !=
extensions()->getElements().end(); ++iter)
{
   cout << left << "element:" << (*iter)->getName() << " (" <<
(*iter)->getValue() << ")" << endl;
}


2018-06-05 19:55 GMT+02:00 Lee Hicks <notifications@github.com>:

**Comment by mr337** [comment]
Thanks for the info. PR https://github.com/irdvo/gpxlib/pull/3 updated and this is the outpout on the test input:
```
Track:1
  Name        : Test
  Comment     : 
  Description : 
  Source      : 
  Type        : 
  Number      : 
  Segments:   : 1

  Segment     : 1
    Latitude    Longitude   Elevation   Time                 Name     Comment    Extensions 
           50.7         6.4                                  trkpt               pass_through:True, 
```

**Comment by mr337** [comment]
I think this issue has been fixed by PR https://github.com/irdvo/gpxlib/pull/3 with test output. Be closing....
