### ISSUE TITLE
Trkpt extensions not read correctly all the time

### ISSUE THREAD

**Issue by mr337** [irdvo/gpxlib#7]
I have been scratching my head on an extension that doesn't always get read correctly from the gpx file, only partial of the extension. I am using the PR https://github.com/irdvo/gpxlib/pull/3 to test this.

The trkpt in question is indicated:
```
<trkpt lon="-93.297037712" lat="37.126846613">
    <extensions>
     <type>cleanup</type>
    </extensions>
   </trkpt>
<trkpt lon="-93.297037695" lat="37.126847159"> <----- Problem trkpt
    <extensions>
     <type>cleanup</type>
    </extensions>
   </trkpt>
<trkpt lon="-93.297035344" lat="37.126877631">
    <extensions>
     <type>cleanup</type>
    </extensions>
   </trkpt>
```

Output
```
$ ./gpxtrk /tmp/sample.txt
    .
    .
    .
    37.12684661 -93.2970377                                  trkpt               type:cleanup, 
    37.12684715 -93.2970376                                  trkpt               type:up, 
    37.12687763 -93.2970353                                  trkpt               type:cleanup,
```

What is confusing is modifying the GPX file, changing number of trkpts or bulk `s/cleanup/blah/` will print the extensions correctly.

Sample file:  [sample.txt](https://github.com/irdvo/gpxlib/files/2581031/sample.txt)

I have tried to investigate the source but my debugging skills are lacking :)
```
(gdb) p (*iter)->getValue()
Couldn't find method gpx::Node::getValue
```

**Comment by mr337** [comment]
Didn't realize gpxlib had some updates. Updated local repo and cannot reproduce issue!

**Comment by irdvo** [comment]
Yes, there was a bug  for bigger gpx-files. If a text part was fed to expat
in two passes, the text was not correctly handled by the gpxlib library.
This was fixed.

Op wo 14 nov. 2018 om 15:50 schreef Lee Hicks <notifications@github.com>:
