### ISSUE TITLE
Why adding new line when level is larger or equal to 0

### ISSUE THREAD

**Issue by willSapgreen** [irdvo/gpxlib#9]
Hello irdvo,
would you mind to explain why adding newline here?
https://github.com/irdvo/gpxlib/blob/f7dcecea86cd5acb8d96bd55f7ff0bade3ecd96a/gpx/Writer.cpp#L143
Thank you.

**Comment by irdvo** [comment]
Hello,

The writer supports two modes: if level is zero, there is no format of the
xml and the xml will be on one line, without indentation and new lines.
If level is bigger then zero, the xml is formatted so there is indentation
and new lines.

Dick


Op zo 24 feb. 2019 om 05:28 schreef WillSapgreen <notifications@github.com>:
